
    create table CondicionOrdenamiento (
        id integer generated by default as identity (start with 1),
        comparador integer,
        indicadorCuenta varchar(255),
        metodologia_id integer not null,
        primary key (id)
    )

    create table CondicionTaxativa (
        id integer generated by default as identity (start with 1),
        expresion varchar(255),
        indicadorOCuenta varchar(255),
        valorAComparar double not null,
        metodologia_id integer not null,
        primary key (id)
    )

    create table Indicador (
        id integer generated by default as identity (start with 1),
        creadoPorUsuario boolean not null,
        formula varchar(255),
        nombre varchar(255),
        sePuedeBorrar boolean not null,
        valores varbinary(255),
        usuario_id integer not null,
        primary key (id)
    )

    create table Metodologia (
        id integer generated by default as identity (start with 1),
        creadoPorUsuario boolean not null,
        nombre varchar(255),
        usuario_id integer not null,
        primary key (id)
    )

    create table Periodo (
        id integer generated by default as identity (start with 1),
        desde varchar(255),
        hasta varchar(255),
        valorCuenta integer not null,
        empresa_cuenta_id integer not null,
        primary key (id)
    )

    create table cuenta (
        id integer generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table empresa (
        id integer generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table empresa_cuenta (
        id integer generated by default as identity (start with 1),
        cuenta_id integer not null,
        empresa_id integer not null,
        primary key (id)
    )

    create table usuario (
        id integer generated by default as identity (start with 1),
        contraseña varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    )

    alter table usuario 
        add constraint UK_cto7dkti4t38iq8r4cqesbd8k  unique (nombre)

    alter table CondicionOrdenamiento 
        add constraint FK_7wjrhfe61pgt5mcc8xixdhekf 
        foreign key (metodologia_id) 
        references Metodologia

    alter table CondicionTaxativa 
        add constraint FK_jc78g1e1jggd0ut46jvbemyhr 
        foreign key (metodologia_id) 
        references Metodologia

    alter table Indicador 
        add constraint FK_554mknaj63vhq3ygex76nbp8q 
        foreign key (usuario_id) 
        references usuario

    alter table Metodologia 
        add constraint FK_psbhp8hh04t8kb8erf54sy618 
        foreign key (usuario_id) 
        references usuario

    alter table Periodo 
        add constraint FK_7jnp0gq18y193thmp8mmckmdt 
        foreign key (empresa_cuenta_id) 
        references empresa_cuenta

    alter table empresa_cuenta 
        add constraint FK_6132h1ce1padjstbjs5c1kjm2 
        foreign key (cuenta_id) 
        references cuenta

    alter table empresa_cuenta 
        add constraint FK_e6t9avpjxoc6l66lfm1s6c7q0 
        foreign key (empresa_id) 
        references empresa
