
    create table CondicionTaxativa (
        id integer generated by default as identity (start with 1),
        expresion varchar(255),
        indicadorOCuenta varchar(255),
        valorAComparar integer not null,
        metodologia_id integer not null,
        primary key (id)
    )

    create table Cuenta (
        id integer generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Cuenta_Empresa (
        cuentas_id integer not null,
        empresas_id integer not null
    )

    create table Empresa (
        id integer generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Indicador (
        id integer generated by default as identity (start with 1),
        formula varchar(255),
        nombre varchar(255),
        sePuedeBorrar boolean not null,
        usuario_id integer not null,
        primary key (id)
    )

    create table Metodologia (
        id integer generated by default as identity (start with 1),
        nombre varchar(255),
        usuario_id integer not null,
        primary key (id)
    )

    create table Periodo (
        id integer generated by default as identity (start with 1),
        desde varchar(255),
        hasta varchar(255),
        valorCuenta integer not null,
        cuenta_id integer not null,
        primary key (id)
    )

    create table usuario (
        id integer generated by default as identity (start with 1),
        contraseña varchar(255),
        nombre varchar(255),
        primary key (id)
    )

    alter table CondicionTaxativa 
        add constraint FK_jc78g1e1jggd0ut46jvbemyhr 
        foreign key (metodologia_id) 
        references Metodologia

    alter table Cuenta_Empresa 
        add constraint FK_smx6xpcbe2iqlejsvsdi73up 
        foreign key (empresas_id) 
        references Empresa

    alter table Cuenta_Empresa 
        add constraint FK_22lw3uejk3itqg57vs4we36xj 
        foreign key (cuentas_id) 
        references Cuenta

    alter table Indicador 
        add constraint FK_554mknaj63vhq3ygex76nbp8q 
        foreign key (usuario_id) 
        references usuario

    alter table Metodologia 
        add constraint FK_psbhp8hh04t8kb8erf54sy618 
        foreign key (usuario_id) 
        references usuario

    alter table Periodo 
        add constraint FK_g0w4y5o2ihcmmvvccqht5bqo4 
        foreign key (cuenta_id) 
        references Cuenta
