/* Generated By:JavaCC: Do not edit this line. GrammarCondicionesConstants.java */
package parserCondiciones;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammarCondicionesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAYOR = 5;
  /** RegularExpression Id. */
  int MENOR = 6;
  /** RegularExpression Id. */
  int IGUAL = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int EXPRESION = 9;
  /** RegularExpression Id. */
  int VARIABLE = 10;
  /** RegularExpression Id. */
  int NUM = 11;
  /** RegularExpression Id. */
  int LEFT_PAREN = 12;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int LETTER = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" mayor\"",
    "\" menor \"",
    "\" igual\"",
    "\"-\"",
    "<EXPRESION>",
    "<VARIABLE>",
    "<NUM>",
    "\"(\"",
    "\")\"",
    "<DIGIT>",
    "<LETTER>",
  };

}
